"use client";

import type { PlayerTournamentRoundDto, TournamentDto, TournamentRewardDetailDto, TournamentSettlementDto } from "@mtg-market/contracts";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { useDecksQuery } from "../../api/decks-api";
import { ApiClientError } from "../../api/client";
import { tournamentsApi, usePlayerTournamentGrantsQuery, usePlayerTournamentQuery, usePlayerTournamentRegistrationsQuery, usePlayerTournamentResultQuery, usePlayerTournamentRoundsQuery, usePlayerTournamentsQuery, useTournamentCommand, useTournamentGrantsQuery, useTournamentHistoryQuery, useTournamentRegistrationQuery, useTournamentResultQuery, useTournamentsQuery } from "../../api/tournaments-api";
import { EmptyState, ErrorState, PageSkeleton } from "../../components/ui";
import { formatMoney } from "../../utils/money";
import styles from "./tournaments-page.module.css";

const kindLabel = { single: "NPC 单场", swiss: "NPC 瑞士轮", prereg: "NPC 预报名" } as const;
const statusLabel = { open: "可报名", settling: "服务端结算中", settled: "已结算", cancelled: "已取消" } as const;
const playerStatusLabel = { open: "开放报名", in_progress: "进行中", settled: "已结算", disputed: "争议处理中", cancelled: "已取消" } as const;
function date(value: string | null) { return value ? new Date(value).toLocaleString("zh-CN") : "—"; }
function error(error: unknown) { return error instanceof ApiClientError ? error.message : "请求未完成，请刷新后重试。"; }
function reward(detail: TournamentRewardDetailDto) { return detail.kind === "pack" ? `补充包奖励（${detail.packId ?? "服务端配置"}）` : detail.kind === "sku" ? `单卡奖励（${detail.skuId ?? "服务端配置"}）` : detail.kind === "GAME_CREDIT" ? "游戏币奖励" : "本次无额外奖励"; }

function NpcReplay({ result }: { result: TournamentSettlementDto }) {
  return <details className={styles.replay}><summary>查看 NPC 可公开重放材料</summary><p>随机种子：<code>{result.replay.seed}</code>；玩家评分 {result.replay.playerScore}；瑞士晋级线 {result.replay.swissCut}。</p><ul>{result.replay.rounds.map((round) => <li key={`${round.stage}-${round.round}`}>第 {round.round} 轮 · {round.stage} · 对阵 {round.opponentName} · 服务端结果：{round.outcome}</li>)}</ul><p className={styles.muted}>NPC 分数、排名和奖励已由服务端固定；重放材料仅用于核对，不会在浏览器重新结算。</p></details>;
}

function NpcResult({ tournamentId, registered }: { tournamentId: string; registered: boolean }) {
  const result = useTournamentResultQuery(tournamentId, registered);
  if (!registered) return null;
  if (result.isPending) return <p className={styles.muted} aria-busy="true">正在读取服务端结算状态…</p>;
  if (result.isError) return <p className={styles.error}>结算状态可能过期：{error(result.error)} <button className="text-button" onClick={() => void result.refetch()}>立即刷新</button></p>;
  const value = result.data?.data.result;
  return value ? <section className={styles.result}><h3>服务端赛事结果</h3><p>排名 {value.rank} · {value.points} 分 · 胜/平/负 {value.wins}/{value.draws}/{value.losses} · 轮空 {value.byes} · 弃权 {value.forfeits}</p><p>奖励：{formatMoney(value.reward)}；{reward(value.rewardDetail)}。排名池与随机池命中均以服务端本次结果为准。</p><NpcReplay result={value} /></section> : <p className={styles.pending}>已报名，正在等待服务端结算。请刷新查看最新状态。</p>;
}

function RegisterDialog({ tournament, onClose }: { tournament: TournamentDto; onClose: () => void }) {
  const decks = useDecksQuery(); const register = useTournamentCommand((token, input: { deckId: string }, key) => tournamentsApi.register(token, tournament.id, input.deckId, key)); const lock = useRef(false); const [deckId, setDeckId] = useState("");
  const selected = decks.data?.data.items.find((deck) => deck.id === deckId);
  const submit = () => { if (!deckId || lock.current) return; lock.current = true; register.mutate({ deckId }, { onSuccess: onClose, onError: () => { lock.current = false; } }); };
  return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="tournament-register-title"><h2 id="tournament-register-title">确认报名</h2><p>赛事：{kindLabel[tournament.kind]}；报名费 {formatMoney(tournament.entryFee)}；服务器将在确认时重新检查卡组、禁牌版本、评分来源和可用库存。</p>{decks.isPending ? <p aria-busy="true">正在读取服务端卡组…</p> : decks.isError ? <p className={styles.error}>卡组读取失败，请关闭后重试。</p> : <label>选择已保存 Commander 卡组<select aria-label="报名卡组" value={deckId} onChange={(event) => setDeckId(event.target.value)}><option value="">请选择</option>{decks.data?.data.items.map((deck) => <option value={deck.id} key={deck.id}>{deck.name}（{deck.legality.valid ? "服务端检查通过" : "存在问题"}）</option>)}</select></label>}{selected ? <p className={styles.muted}>当前服务端保存状态：{selected.legality.valid ? "上次检查通过" : selected.legality.issues.join("；")}。最终资格只以报名响应为准。</p> : null}{register.isError ? <p className={styles.error} role="alert">{error(register.error)}</p> : null}<div className="actions"><button className="button secondary" disabled={register.isPending} onClick={onClose}>取消</button><button className="button" disabled={!deckId || register.isPending} onClick={submit}>{register.isPending ? "正在由服务端报名…" : "确认报名"}</button></div></section></div>;
}

function TournamentCard({ tournament }: { tournament: TournamentDto }) {
  const registration = useTournamentRegistrationQuery(tournament.id, tournament.registered); const [dialog, setDialog] = useState(false);
  return <article className={styles.card}><div className={styles.cardHead}><div><h2>{kindLabel[tournament.kind]}</h2><p className={styles.muted}>{tournament.naturalDate} · {tournament.totalSeats} 个总座位 · 难度 {tournament.difficulty}</p></div><span className={styles.badge}>{statusLabel[tournament.status]}</span></div><p>报名费：{formatMoney(tournament.entryFee)}。规则：{tournament.ruleVersion}。</p><p className={styles.muted}>开放 {date(tournament.opensAt)}{tournament.cutoffAt ? `；截止 ${date(tournament.cutoffAt)}` : "；报名后由服务端投递结算"}。</p>{tournament.registered ? <><p className={styles.success}>已报名{registration.data ? `；评分快照来源 ${registration.data.data.registration.powerSnapshot.source}` : ""}。</p><NpcResult tournamentId={tournament.id} registered /></> : <button className="button" disabled={tournament.status !== "open"} onClick={() => setDialog(true)}>{tournament.status === "open" ? "报名预览与确认" : "当前不可报名"}</button>}{dialog ? <RegisterDialog tournament={tournament} onClose={() => setDialog(false)} /> : null}</article>;
}

function PackGrants() {
  const npc = useTournamentGrantsQuery(); const player = usePlayerTournamentGrantsQuery(); const claimNpc = useTournamentCommand((token, id: string, key) => tournamentsApi.claimGrant(token, id, key)); const claimPlayer = useTournamentCommand((token, id: string, key) => tournamentsApi.claimPlayerGrant(token, id, key));
  const items = [...(npc.data?.data.items ?? []).map((grant) => ({ ...grant, source: "npc" as const })), ...(player.data?.data.items ?? []).map((grant) => ({ ...grant, source: "player" as const }))];
  return <section className={styles.section}><h2>可领取的随机奖励补充包</h2>{npc.isError || player.isError ? <p className={styles.error}>奖励状态读取失败，请刷新。</p> : items.length === 0 ? <p className={styles.muted}>当前没有待领取的补充包奖励。</p> : <ul className={styles.grants}>{items.map((grant) => <li key={`${grant.source}-${grant.id}`}><span>赛事奖励 · 补充包 {grant.packId} · {grant.status === "available" ? "待领取" : "已领取"}</span><button className="button secondary" disabled={grant.status !== "available" || claimNpc.isPending || claimPlayer.isPending} onClick={() => (grant.source === "npc" ? claimNpc : claimPlayer).mutate(grant.id)}>领取并由服务端开包</button></li>)}</ul>}</section>;
}

export function TournamentsPage() {
  const tournaments = useTournamentsQuery(); const history = useTournamentHistoryQuery();
  if (tournaments.isPending) return <PageSkeleton label="正在加载今日赛事" />;
  if (tournaments.isError) return <main className="page"><ErrorState title="今日赛事加载失败" onRetry={() => void tournaments.refetch()} /></main>;
  return <main className="page"><p className="eyebrow">服务端赛事与奖励</p><div className={styles.pageHead}><div><h1>今日比赛</h1><p className="intro">赛程、报名、结算、排名、奖励和 NPC 重放均由服务端确定。页面只展示结果与提交意图。</p></div><Link className="button secondary" href="/tournaments/create">创建玩家赛事</Link></div>{tournaments.data.data.items.length === 0 ? <EmptyState title="今日没有可用比赛">服务端尚未为当前业务日生成个人 NPC 赛事；请稍后刷新。</EmptyState> : <div className={styles.grid}>{tournaments.data.data.items.map((tournament) => <TournamentCard tournament={tournament} key={tournament.id} />)}</div>}<PackGrants /><section className={styles.section}><h2>历史赛事</h2>{history.isPending ? <p aria-busy="true">正在读取历史赛事…</p> : history.isError ? <p className={styles.error}>历史读取失败。<button className="text-button" onClick={() => void history.refetch()}>重试</button></p> : history.data?.data.items.length === 0 ? <p className={styles.muted}>尚无已报名的历史赛事。</p> : <ul className={styles.history}>{history.data.data.items.map((item) => <li key={item.tournament.id}><strong>{kindLabel[item.tournament.kind]} · {item.tournament.naturalDate}</strong><span>{item.result ? `排名 ${item.result.rank}，奖励 ${formatMoney(item.result.reward)}` : "尚未结算"}</span>{item.result ? <NpcReplay result={item.result} /> : null}</li>)}</ul>}</section><section className={styles.section}><h2>我的玩家赛事</h2><PlayerTournamentList /></section></main>;
}

function PlayerTournamentList() { const list = usePlayerTournamentsQuery(); if (list.isPending) return <p aria-busy="true">正在读取玩家赛事…</p>; if (list.isError) return <p className={styles.error}>玩家赛事读取失败。</p>; if (!list.data?.data.items.length) return <p className={styles.muted}>尚未创建或参加玩家赛事。</p>; return <ul className={styles.history}>{list.data.data.items.map((tournament) => <li key={tournament.id}><strong>{tournament.name}</strong><span>{tournament.mode === "game" ? "游戏内对局" : "现实桌瑞士轮"} · {playerStatusLabel[tournament.status]}</span><Link className="text-button" href={`/tournaments/player/${tournament.id}`}>查看赛事</Link></li>)}</ul>; }

export function CreatePlayerTournamentPage() {
  const router = useRouter(); const [mode, setMode] = useState<"game" | "tabletop">("game"); const [name, setName] = useState(""); const create = useTournamentCommand((token, input: { mode: "game" | "tabletop"; name: string }, key) => tournamentsApi.createPlayer(token, input.mode, input.name, key));
  return <main className="page"><p className="eyebrow">玩家创建赛事</p><h1>创建比赛</h1><p className="intro">游戏内对局只使用服务端卡组快照和结算；现实桌瑞士轮仅保存你填写的卡组名称，不读取、保存或锁定实体卡组。</p><section className={styles.section}><label>赛事名称<input aria-label="赛事名称" value={name} onChange={(event) => setName(event.target.value)} maxLength={100} /></label><fieldset><legend>赛事类型</legend><label><input type="radio" checked={mode === "game"} onChange={() => setMode("game")} /> 游戏内对局</label><label><input type="radio" checked={mode === "tabletop"} onChange={() => setMode("tabletop")} /> 现实桌瑞士轮</label></fieldset>{create.isError ? <p className={styles.error}>{error(create.error)}</p> : null}<button className="button" disabled={!name.trim() || create.isPending} onClick={() => create.mutate({ mode, name: name.trim() }, { onSuccess: ({ data }) => router.push(`/tournaments/player/${data.tournamentId}`) })}>{create.isPending ? "正在创建…" : "创建服务器赛事"}</button></section></main>;
}

function RoundCard({ round, registrations }: { round: PlayerTournamentRoundDto; registrations: Array<{ id: string; points: number }> }) {
  const [winner, setWinner] = useState(""); const [draw, setDraw] = useState(false); const submit = useTournamentCommand((token, input: { id: string; body: { winnerRegistrationId: string | null; draw: boolean; forfeitedRegistrationIds: string[] } }, key) => tournamentsApi.submitRound(token, input.id, input.body, key)); const confirm = useTournamentCommand((token, id: string, key) => tournamentsApi.confirmRound(token, id, key));
  const players = registrations.filter((registration) => round.registrationIds.includes(registration.id));
  return <article className={styles.round}><h3>第 {round.roundNumber} 轮 · 第 {round.tableNumber} 桌 · {round.stage === "playoff" ? "奖励位加赛" : "常规轮"}</h3><p>同桌报名：{players.map((player) => `#${player.id.slice(0, 8)}（${player.points} 分）`).join("、") || "服务端尚未返回"}</p><p className={styles.muted}>规则：胜 4 分、平局全桌各 1 分、负/弃权/退出 0 分。状态：{round.status}。</p>{round.status === "pending" || round.status === "submitted" ? <div className={styles.roundActions}><label>胜者<select aria-label={`第 ${round.roundNumber} 轮胜者`} value={winner} disabled={draw} onChange={(event) => setWinner(event.target.value)}><option value="">选择同桌报名</option>{players.map((player) => <option key={player.id} value={player.id}>#{player.id.slice(0, 8)}</option>)}</select></label><label><input type="checkbox" checked={draw} onChange={(event) => setDraw(event.target.checked)} /> 全桌平局</label><button className="button secondary" disabled={submit.isPending || (!draw && !winner)} onClick={() => submit.mutate({ id: round.id, body: { winnerRegistrationId: draw ? null : winner, draw, forfeitedRegistrationIds: [] } })}>提交本轮赛果</button><button className="button" disabled={confirm.isPending} onClick={() => confirm.mutate(round.id)}>确认本轮赛果</button></div> : null}{submit.isError || confirm.isError ? <p className={styles.error}>服务器拒绝或请求失败：{error(submit.error ?? confirm.error)}</p> : null}<p className={styles.muted}>只有已报名同桌玩家才会被服务端允许提交或确认；本页不会自行判定权限或记分。</p></article>;
}

export function PlayerTournamentDetailPage() {
  const params = useParams<{ tournamentId: string }>(); const id = params.tournamentId; const tournament = usePlayerTournamentQuery(id); const registrations = usePlayerTournamentRegistrationsQuery(id); const rounds = usePlayerTournamentRoundsQuery(id); const result = usePlayerTournamentResultQuery(id); const decks = useDecksQuery(); const [deckId, setDeckId] = useState(""); const [deckName, setDeckName] = useState(""); const join = useTournamentCommand((token, input: { id: string; body: { deckId: string } | { deckName: string } }, key) => tournamentsApi.joinPlayer(token, input.id, input.body, key)); const start = useTournamentCommand((token, idValue: string, key) => tournamentsApi.start(token, idValue, key)); const pair = useTournamentCommand((token, idValue: string, key) => tournamentsApi.pair(token, idValue, key)); const settle = useTournamentCommand((token, idValue: string, key) => tournamentsApi.settle(token, idValue, key));
  if (tournament.isPending) return <PageSkeleton label="正在加载玩家赛事" />; if (tournament.isError || !tournament.data) return <main className="page"><ErrorState title="玩家赛事加载失败或无权查看" onRetry={() => void tournament.refetch()} /></main>;
  const value = tournament.data.data.tournament; const people = registrations.data?.data.items ?? [];
  return <main className="page"><Link className="text-button" href="/tournaments">← 返回比赛</Link><p className="eyebrow">{value.mode === "game" ? "游戏内对局" : "现实桌瑞士轮"}</p><h1>{value.name}</h1><p className="intro">状态：{playerStatusLabel[value.status]}；规则版本 {value.ruleVersion}。所有配对、积分、排名和奖励均以服务端响应为准。</p><section className={styles.section}><h2>报名与开赛</h2>{value.mode === "game" ? <label>选择服务端保存的卡组<select aria-label="游戏内赛事卡组" value={deckId} onChange={(event) => setDeckId(event.target.value)}><option value="">请选择</option>{decks.data?.data.items.map((deck) => <option key={deck.id} value={deck.id}>{deck.name}</option>)}</select></label> : <label>现实桌卡组名称<input aria-label="现实桌卡组名称" value={deckName} onChange={(event) => setDeckName(event.target.value)} maxLength={100} /></label>}<div className="actions"><button className="button" disabled={join.isPending || (value.mode === "game" ? !deckId : !deckName.trim())} onClick={() => join.mutate({ id, body: value.mode === "game" ? { deckId } : { deckName: deckName.trim() } })}>报名</button>{value.mode === "game" ? <button className="button secondary" disabled={start.isPending} onClick={() => start.mutate(id)}>开始并等待服务端结算</button> : <><button className="button secondary" disabled={pair.isPending} onClick={() => pair.mutate(id)}>由服务端生成本轮配对</button><button className="button secondary" disabled={settle.isPending} onClick={() => settle.mutate(id)}>请求服务端结算</button></>}</div>{join.isError || start.isError || pair.isError || settle.isError ? <p className={styles.error}>{error(join.error ?? start.error ?? pair.error ?? settle.error)}</p> : null}</section><section className={styles.section}><h2>当前报名与排名</h2>{registrations.isPending ? <p aria-busy="true">正在读取报名…</p> : <ul className={styles.history}>{people.map((person) => <li key={person.id}><strong>报名 #{person.id.slice(0, 8)}</strong><span>{person.mode === "tabletop" ? `卡组名：${person.deckName}` : "游戏内卡组由服务端快照保存"} · {person.points} 分 · {person.status}</span></li>)}</ul>}</section>{value.mode === "tabletop" ? <section className={styles.section}><h2>现实桌轮次与全桌确认</h2>{rounds.isPending ? <p aria-busy="true">正在读取轮次…</p> : rounds.data?.data.items.length === 0 ? <p className={styles.muted}>尚未生成配对。</p> : rounds.data?.data.items.map((round) => <RoundCard key={round.id} round={round} registrations={people} />)}</section> : null}<section className={styles.section}><h2>服务端结果</h2>{result.isPending ? <p aria-busy="true">正在等待或读取结算…</p> : result.isError ? <p className={styles.pending}>尚无你的已结算结果；结算任务可能仍在执行，可刷新查看。</p> : result.data ? <p>排名 {result.data.data.result.rank} · {result.data.data.result.points} 分 · 奖励 {formatMoney(result.data.data.result.reward)}；{reward(result.data.data.result.rewardDetail)}。</p> : null}</section></main>;
}
