import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { openSqliteDatabase } from "@mtg-market/database";
import { createApiApp } from "../../../app.js";
import { loadApiConfig } from "../../../config/environment.js";
import { DeckService } from "../application/deck-service.js";

const directories: string[] = [];
afterEach(() => directories.splice(0).forEach((directory) => rmSync(directory, { recursive: true, force: true })));
async function setup() { const directory = mkdtempSync(join(tmpdir(), "mtg-decks-")); directories.push(directory); const path = join(directory, "test.db"); const database = openSqliteDatabase(path); const app = await createApiApp(loadApiConfig({ APP_ENV: "test", SQLITE_PATH: path, AUTH_JWT_SECRET: "test-only-secret-must-be-at-least-32-characters" }), database); return { app, database }; }
async function player(app: Awaited<ReturnType<typeof setup>>["app"]) { const registration = await app.inject({ method: "POST", url: "/v1/auth/register", payload: { email: `deck-${Math.random()}@example.test`, displayName: "构筑测试", password: "correct-horse-battery-staple" } }); const authorization = `Bearer ${registration.json().data.accessToken as string}`; await app.inject({ method: "POST", url: "/v1/archive", headers: { authorization, "idempotency-key": "deck-archive-key-0001" }, payload: {} }); return { authorization, userId: registration.json().data.user.id as string }; }
function seed(database: ReturnType<typeof openSqliteDatabase>, userId: string) { const now = "2026-07-29T00:00:00.000Z"; const set = "10000000-0000-4000-8000-000000000241"; const printing = "20000000-0000-4000-8000-000000000241"; const sku = "30000000-0000-4000-8000-000000000241"; database.prepare("INSERT INTO card_sets (id, code, name, source, created_at) VALUES (?, 'DEK', '构筑测试', 'manual-test', ?)").run(set, now); database.prepare("INSERT INTO card_printings (id, set_id, name, collector_number, scryfall_id, oracle_id, oracle_text, rarity, legalities_json, color_identity_json, type_line, keywords_json, mana_value, source, source_reference, is_manual_exception, created_at, updated_at) VALUES (?, ?, '赤焰统帅', '1', NULL, 'oracle-red-commander', '', 'rare', '{\"commander\":\"legal\"}', '[\"R\"]', 'Legendary Creature — Human', '[]', 3, 'manual-test', 'fixture', 1, ?, ?)").run(printing, set, now, now); database.prepare("INSERT INTO card_skus (id, printing_id, finish, tradable, source, source_reference, is_manual_exception, created_at, updated_at) VALUES (?, ?, 'nonfoil', 0, 'manual-test', 'fixture', 1, ?, ?)").run(sku, printing, now, now); database.prepare("INSERT INTO inventory_holdings (id, user_id, sku_id, quantity, available_quantity, order_locked_quantity, tournament_locked_quantity, average_cost_amount, market_value_amount, market_value_captured_at, updated_at) VALUES (?, ?, ?, 1, 1, 0, 0, 0, NULL, NULL, ?)").run("holding-241", userId, sku, now); return sku; }
describe("I24B 卡组草稿路由", () => {
  it("保存合法草稿只记录卡组与审计，不创建库存锁定；同键重放不重复写入", async () => { const { app, database } = await setup(); const { authorization, userId } = await player(app); const commanderSku = seed(database, userId); const body = { name: "红色山脉", cards: [{ zone: "commander", skuId: commanderSku, quantity: 1 }, { zone: "virtual_basic", virtualBasic: "mountain", quantity: 99 }] }; const request = { method: "POST" as const, url: "/v1/decks", headers: { authorization, "idempotency-key": "deck-create-key-0001" }, payload: body }; const [first, replay] = await Promise.all([app.inject(request), app.inject(request)]); expect([first.statusCode, replay.statusCode]).toEqual([201, 201]); const created = first.json().data; expect(created).toMatchObject({ legality: { valid: true, totalCards: 100, ruleVersion: "commander-100/v1" }, strengthSnapshot: null }); expect(database.prepare("SELECT COUNT(*) AS count FROM inventory_holds").get()).toEqual({ count: 0 }); expect(database.prepare("SELECT available_quantity, tournament_locked_quantity FROM inventory_holdings").get()).toEqual({ available_quantity: 1, tournament_locked_quantity: 0 }); expect(database.prepare("SELECT COUNT(*) AS count FROM decks").get()).toEqual({ count: 1 }); await app.close(); database.close(); });
  it("以服务端元数据报告库存不足和非法构筑，同时不拒绝保存草稿", async () => { const { app, database } = await setup(); const { authorization, userId } = await player(app); const commanderSku = seed(database, userId); const invalid = { name: "缺库存草稿", cards: [{ zone: "commander", skuId: commanderSku, quantity: 1 }, { zone: "virtual_basic", virtualBasic: "island", quantity: 99 }] }; const validation = await app.inject({ method: "POST", url: "/v1/decks/validate", headers: { authorization }, payload: invalid }); expect(validation.json()).toMatchObject({ ok: true, data: { valid: false } }); expect(validation.json().data.issues.join("\n")).toMatch(/颜色/); const saved = await app.inject({ method: "POST", url: "/v1/decks", headers: { authorization, "idempotency-key": "deck-invalid-key-0001" }, payload: invalid }); expect(saved.statusCode).toBe(201); expect(saved.json().data.legality.valid).toBe(false); await app.close(); database.close(); });
  it("为未来报名追加 Leyline 快照和加密源记录，不把完整响应放进草稿 DTO", async () => { const { app, database } = await setup(); const { authorization, userId } = await player(app); const commanderSku = seed(database, userId); const saved = await app.inject({ method: "POST", url: "/v1/decks", headers: { authorization, "idempotency-key": "deck-snapshot-key-0001" }, payload: { name: "评分候选", cards: [{ zone: "commander", skuId: commanderSku, quantity: 1 }, { zone: "virtual_basic", virtualBasic: "mountain", quantity: 99 }] } }); const deckId = saved.json().data.id as string; const snapshot = new DeckService(database).saveLeylineSnapshot({ userId, deckId, registrationId: "registration-fixture-001", encryptionKey: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=", evaluation: { score: 100, providerAlgorithmVersion: "undeclared", decklistText: "*1 Commander", inputSummarySha256: "a".repeat(64), responseSha256: "b".repeat(64), details: { scores: { power: 100 }, bracket: 4, tiers: [], combos: [], computedAt: null, resolvedCount: 100, missingCards: [], isStale: false }, rawResponse: { scores: { power: 100 }, privateProviderField: "do-not-return" } } }); expect(snapshot).toMatchObject({ source: "leyline", score: 100, providerAlgorithmVersion: "undeclared" }); expect(database.prepare("SELECT response_sha256, length(encrypted_response) AS encrypted_size FROM deck_leyline_source_records").get()).toMatchObject({ response_sha256: "b".repeat(64), encrypted_size: expect.any(Number) }); expect(saved.json().data).not.toHaveProperty("rawResponse"); await app.close(); database.close(); });
});
